title: Seja bem vindo! Sou Rafael Camarda e utilizo esse espaço para falar sobre assuntos que me vem a mente!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rafael Camarda # add your name
author-img: avatar.jpg # add your photo
about-author: Desenvolvedor Ruby na @locaweb. As vezes também paga de nerd, músico e gamer. # add description
twitter: rafacamarda
facebook:
github: rafaelcamarda # add your Github handle
linkedin: rafaelcamarda
email: rf.camarda@gmail.com

# Disqus
discus-identifier: rafaelcamarda # add your discus identifier

# Tracker
analytics: UA-118119465-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
